/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyAmazonRouteImport } from './routes/why-amazon'
import { Route as SellRouteImport } from './routes/sell'
import { Route as NewReleasesRouteImport } from './routes/new-releases'
import { Route as MobilesRouteImport } from './routes/mobiles'
import { Route as MissionHistoryRouteImport } from './routes/mission-history'
import { Route as GroceryRouteImport } from './routes/grocery'
import { Route as FreshRouteImport } from './routes/fresh'
import { Route as FashionRouteImport } from './routes/fashion'
import { Route as ElectronicsRouteImport } from './routes/electronics'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FreshIndexRouteImport } from './routes/fresh.index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as FreshCategoryIdRouteImport } from './routes/fresh.$categoryId'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutReviewRouteImport } from './routes/checkout.review'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout.payment'
import { Route as CheckoutAddressRouteImport } from './routes/checkout.address'
import { Route as AccountWishlistRouteImport } from './routes/account.wishlist'
import { Route as AccountOrdersRouteImport } from './routes/account.orders'
import { Route as AccountAddressesRouteImport } from './routes/account.addresses'
import { Route as AccountAddressFormRouteImport } from './routes/account.address-form'

const WhyAmazonRoute = WhyAmazonRouteImport.update({
  id: '/why-amazon',
  path: '/why-amazon',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const NewReleasesRoute = NewReleasesRouteImport.update({
  id: '/new-releases',
  path: '/new-releases',
  getParentRoute: () => rootRouteImport,
} as any)
const MobilesRoute = MobilesRouteImport.update({
  id: '/mobiles',
  path: '/mobiles',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionHistoryRoute = MissionHistoryRouteImport.update({
  id: '/mission-history',
  path: '/mission-history',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryRoute = GroceryRouteImport.update({
  id: '/grocery',
  path: '/grocery',
  getParentRoute: () => rootRouteImport,
} as any)
const FreshRoute = FreshRouteImport.update({
  id: '/fresh',
  path: '/fresh',
  getParentRoute: () => rootRouteImport,
} as any)
const FashionRoute = FashionRouteImport.update({
  id: '/fashion',
  path: '/fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectronicsRoute = ElectronicsRouteImport.update({
  id: '/electronics',
  path: '/electronics',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreshIndexRoute = FreshIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FreshRoute,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FreshCategoryIdRoute = FreshCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => FreshRoute,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutReviewRoute = CheckoutReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutAddressRoute = CheckoutAddressRouteImport.update({
  id: '/address',
  path: '/address',
  getParentRoute: () => CheckoutRoute,
} as any)
const AccountWishlistRoute = AccountWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAddressFormRoute = AccountAddressFormRouteImport.update({
  id: '/address-form',
  path: '/address-form',
  getParentRoute: () => AccountRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/deals': typeof DealsRoute
  '/demo': typeof DemoRoute
  '/electronics': typeof ElectronicsRoute
  '/fashion': typeof FashionRoute
  '/fresh': typeof FreshRouteWithChildren
  '/grocery': typeof GroceryRoute
  '/mission-history': typeof MissionHistoryRoute
  '/mobiles': typeof MobilesRoute
  '/new-releases': typeof NewReleasesRoute
  '/sell': typeof SellRoute
  '/why-amazon': typeof WhyAmazonRoute
  '/account/address-form': typeof AccountAddressFormRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/checkout/address': typeof CheckoutAddressRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/fresh/$categoryId': typeof FreshCategoryIdRoute
  '/product/$id': typeof ProductIdRoute
  '/fresh/': typeof FreshIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/deals': typeof DealsRoute
  '/demo': typeof DemoRoute
  '/electronics': typeof ElectronicsRoute
  '/fashion': typeof FashionRoute
  '/grocery': typeof GroceryRoute
  '/mission-history': typeof MissionHistoryRoute
  '/mobiles': typeof MobilesRoute
  '/new-releases': typeof NewReleasesRoute
  '/sell': typeof SellRoute
  '/why-amazon': typeof WhyAmazonRoute
  '/account/address-form': typeof AccountAddressFormRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/checkout/address': typeof CheckoutAddressRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/fresh/$categoryId': typeof FreshCategoryIdRoute
  '/product/$id': typeof ProductIdRoute
  '/fresh': typeof FreshIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/deals': typeof DealsRoute
  '/demo': typeof DemoRoute
  '/electronics': typeof ElectronicsRoute
  '/fashion': typeof FashionRoute
  '/fresh': typeof FreshRouteWithChildren
  '/grocery': typeof GroceryRoute
  '/mission-history': typeof MissionHistoryRoute
  '/mobiles': typeof MobilesRoute
  '/new-releases': typeof NewReleasesRoute
  '/sell': typeof SellRoute
  '/why-amazon': typeof WhyAmazonRoute
  '/account/address-form': typeof AccountAddressFormRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/wishlist': typeof AccountWishlistRoute
  '/checkout/address': typeof CheckoutAddressRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/fresh/$categoryId': typeof FreshCategoryIdRoute
  '/product/$id': typeof ProductIdRoute
  '/fresh/': typeof FreshIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/browse'
    | '/cart'
    | '/checkout'
    | '/deals'
    | '/demo'
    | '/electronics'
    | '/fashion'
    | '/fresh'
    | '/grocery'
    | '/mission-history'
    | '/mobiles'
    | '/new-releases'
    | '/sell'
    | '/why-amazon'
    | '/account/address-form'
    | '/account/addresses'
    | '/account/orders'
    | '/account/wishlist'
    | '/checkout/address'
    | '/checkout/payment'
    | '/checkout/review'
    | '/checkout/success'
    | '/fresh/$categoryId'
    | '/product/$id'
    | '/fresh/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/browse'
    | '/cart'
    | '/checkout'
    | '/deals'
    | '/demo'
    | '/electronics'
    | '/fashion'
    | '/grocery'
    | '/mission-history'
    | '/mobiles'
    | '/new-releases'
    | '/sell'
    | '/why-amazon'
    | '/account/address-form'
    | '/account/addresses'
    | '/account/orders'
    | '/account/wishlist'
    | '/checkout/address'
    | '/checkout/payment'
    | '/checkout/review'
    | '/checkout/success'
    | '/fresh/$categoryId'
    | '/product/$id'
    | '/fresh'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/browse'
    | '/cart'
    | '/checkout'
    | '/deals'
    | '/demo'
    | '/electronics'
    | '/fashion'
    | '/fresh'
    | '/grocery'
    | '/mission-history'
    | '/mobiles'
    | '/new-releases'
    | '/sell'
    | '/why-amazon'
    | '/account/address-form'
    | '/account/addresses'
    | '/account/orders'
    | '/account/wishlist'
    | '/checkout/address'
    | '/checkout/payment'
    | '/checkout/review'
    | '/checkout/success'
    | '/fresh/$categoryId'
    | '/product/$id'
    | '/fresh/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  DealsRoute: typeof DealsRoute
  DemoRoute: typeof DemoRoute
  ElectronicsRoute: typeof ElectronicsRoute
  FashionRoute: typeof FashionRoute
  FreshRoute: typeof FreshRouteWithChildren
  GroceryRoute: typeof GroceryRoute
  MissionHistoryRoute: typeof MissionHistoryRoute
  MobilesRoute: typeof MobilesRoute
  NewReleasesRoute: typeof NewReleasesRoute
  SellRoute: typeof SellRoute
  WhyAmazonRoute: typeof WhyAmazonRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-amazon': {
      id: '/why-amazon'
      path: '/why-amazon'
      fullPath: '/why-amazon'
      preLoaderRoute: typeof WhyAmazonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-releases': {
      id: '/new-releases'
      path: '/new-releases'
      fullPath: '/new-releases'
      preLoaderRoute: typeof NewReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobiles': {
      id: '/mobiles'
      path: '/mobiles'
      fullPath: '/mobiles'
      preLoaderRoute: typeof MobilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-history': {
      id: '/mission-history'
      path: '/mission-history'
      fullPath: '/mission-history'
      preLoaderRoute: typeof MissionHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery': {
      id: '/grocery'
      path: '/grocery'
      fullPath: '/grocery'
      preLoaderRoute: typeof GroceryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fresh': {
      id: '/fresh'
      path: '/fresh'
      fullPath: '/fresh'
      preLoaderRoute: typeof FreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fashion': {
      id: '/fashion'
      path: '/fashion'
      fullPath: '/fashion'
      preLoaderRoute: typeof FashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electronics': {
      id: '/electronics'
      path: '/electronics'
      fullPath: '/electronics'
      preLoaderRoute: typeof ElectronicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fresh/': {
      id: '/fresh/'
      path: '/'
      fullPath: '/fresh/'
      preLoaderRoute: typeof FreshIndexRouteImport
      parentRoute: typeof FreshRoute
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fresh/$categoryId': {
      id: '/fresh/$categoryId'
      path: '/$categoryId'
      fullPath: '/fresh/$categoryId'
      preLoaderRoute: typeof FreshCategoryIdRouteImport
      parentRoute: typeof FreshRoute
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/review': {
      id: '/checkout/review'
      path: '/review'
      fullPath: '/checkout/review'
      preLoaderRoute: typeof CheckoutReviewRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/address': {
      id: '/checkout/address'
      path: '/address'
      fullPath: '/checkout/address'
      preLoaderRoute: typeof CheckoutAddressRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/account/wishlist': {
      id: '/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AccountWishlistRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/addresses': {
      id: '/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/address-form': {
      id: '/account/address-form'
      path: '/address-form'
      fullPath: '/account/address-form'
      preLoaderRoute: typeof AccountAddressFormRouteImport
      parentRoute: typeof AccountRoute
    }
  }
}

interface AccountRouteChildren {
  AccountAddressFormRoute: typeof AccountAddressFormRoute
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountWishlistRoute: typeof AccountWishlistRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAddressFormRoute: AccountAddressFormRoute,
  AccountAddressesRoute: AccountAddressesRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountWishlistRoute: AccountWishlistRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface CheckoutRouteChildren {
  CheckoutAddressRoute: typeof CheckoutAddressRoute
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutReviewRoute: typeof CheckoutReviewRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutAddressRoute: CheckoutAddressRoute,
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutReviewRoute: CheckoutReviewRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface FreshRouteChildren {
  FreshCategoryIdRoute: typeof FreshCategoryIdRoute
  FreshIndexRoute: typeof FreshIndexRoute
}

const FreshRouteChildren: FreshRouteChildren = {
  FreshCategoryIdRoute: FreshCategoryIdRoute,
  FreshIndexRoute: FreshIndexRoute,
}

const FreshRouteWithChildren = FreshRoute._addFileChildren(FreshRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  DealsRoute: DealsRoute,
  DemoRoute: DemoRoute,
  ElectronicsRoute: ElectronicsRoute,
  FashionRoute: FashionRoute,
  FreshRoute: FreshRouteWithChildren,
  GroceryRoute: GroceryRoute,
  MissionHistoryRoute: MissionHistoryRoute,
  MobilesRoute: MobilesRoute,
  NewReleasesRoute: NewReleasesRoute,
  SellRoute: SellRoute,
  WhyAmazonRoute: WhyAmazonRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
